//models/categories.dart
class SportCategories {
  static const List<String> list = [
    'American Football',
    'Archery',
    'Athletics',
    'Badminton',
    'Baseball',
    'Basketball',
    'Bodybuilding',
    'Boxing',
    'Canoeing',
    'Cricket',
    'CrossFit',
    'Cycling',
    'Dancing',
    'Darts',
    'Dodgeball',
    'F1',
    'Football',
    'Golf',
    'Gymnastics',
    'Handball',
    'Hockey',
    'Horse Riding',
    'Ice Hockey',
    'Ice Skating',
    'Jujutsu',
    'Karate',
    'Kayaking',
    'Kickboxing',
    'Martial Arts',
    'Muay Thai',
    'Nascar',
    'Netball',
    'Powerlifting',
    'Rally Racing',
    'Rock Climbing',
    'Rowing',
    'Rugby',
    'Sailing',
    'Skateboarding',
    'Skiing',
    'Snooker',
    'Snowboarding',
    'Squash',
    'Surfing',
    'Swimming',
    'Table Tennis',
    'Tennis',
    'Trampolining',
    'Volleyball',
    'Wakeboarding',
    'Water Polo',
    'Windsurfing',
    'Wrestling',
  ];
}
